# Generated by Django 5.0.1 on 2024-01-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('PersonID', models.IntegerField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=10)),
            ],
        ),
    ]
